# WORK IN PROGRESS
services:
  user-history:
    build:
      context: .
      dockerfile: services/user-history/Dockerfile
    expose: 
      - '8001'
    # ports: ["8001:801"]
    env_file:
      - .env

  chat-inference:
    build:
      context: .
      dockerfile: services/chat-inference/Dockerfile
    expose: 
      - '8002'
    # ports: ["8002:8002"]
    env_file:
      - .env

  user-profile:
    build:
      context: .
      dockerfile: services/user-profile/Dockerfile
    expose: 
      - '8003'
    # ports: ["8003:8003"]
    env_file:
      - .env

  personalization:
    build:
      context: .
      dockerfile: services/personalization/Dockerfile
    expose: 
      - '8004'
    # ports: ["8004:8004"]
    env_file:
      - .env
  
  api-gateway:
    build:
      context: .
      dockerfile: services/api-gateway/Dockerfile
    ports: ["80:8000"]
    depends_on:
      - user-history
      - chat-inference
      - user-profile
      - personalization
      - ext-tools
    env_file:
      - .env
  
  ext-tools:
    build:
      context: .
      dockerfile: services/ext-tools/Dockerfile
    expose: 
      - '8005'
    # ports: ["8005:8005"]
    env_file:
      - .env

networks:
  backend:
    driver: bridge

  # postgres:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_USER: app
  #     POSTGRES_PASSWORD: secret
  #     POSTGRES_DB: appdb
  #   ports: ["5432:5432"]

  # redis:
  #   image: redis:6
  #   ports: ["6379:6379"]
